#include "Video.h"


Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
char keyboard; //input from keyboard

void help();
void processVideo(char* videoFilename);
void processImages(char* firstFrameFilename);


int Video()
{

	help();
	string filename = "video1.mp4";
	VideoCapture capture(filename);
	Mat frame;

	if (!capture.isOpened())
		throw "Error when reading video";

	namedWindow("video", 1);


	for (;;)
	{
		capture >> frame;
		if (frame.empty())
		{
			break;
		}
		//pMOG2->apply(frame, fgMaskMOG2);
		/*stringstream ss;
		rectangle(frame, cv::Point(10, 2), cv::Point(100, 20),
			cv::Scalar(255, 255, 255), -1);
		ss << capture.get(CAP_PROP_POS_FRAMES);

		string frameNumberString = ss.str();
		putText(frame, frameNumberString.c_str(), cv::Point(15, 15),
			FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0, 0, 0));
		//show the current frame and the fg masks*/
		imshow("Frame", frame);
		//imshow("FG Mask MOG 2", fgMaskMOG2);


		//imshow("video", frame);




		waitKey(20);
		if (waitKey(10) == 27) break;
	}
	return 0;

}

void help()
{
	cout
		<< "--------------------------------------------------------------------------" << endl
		<< "This program shows how to use background subtraction methods provided by " << endl
		<< " OpenCV. You can process both videos (-vid) and images (-img)." << endl
		<< endl
		<< "Usage:" << endl
		<< "./bg_sub {-vid <video filename>|-img <image filename>}" << endl
		<< "for example: ./bg_sub -vid video.avi" << endl
		<< "or: ./bg_sub -img /data/images/1.png" << endl
		<< "--------------------------------------------------------------------------" << endl
		<< endl;
}
